### PR TITLE
Cm messages

### PR DESCRIPTION
**Pull request by bluemorgan23**
# Description

This pull request contains all of the functionality and styling for the Messages component.

Applies to issue # ChatRoom

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

1. git fetch --all
2. git checkout cm-messages
3. cd api and run json-server
4. npm start
5. code .
6. Login
7. Check messages component by sending a message, checking to see if the POST works.
8. Check the edit functionality by trying to edit a message and checking to see if the PUT works.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Alex-Thacker — DISMISSED** [review]
works

**Review by SamBritt — DISMISSED** [review]
Cool bro

**Review by SamBritt — DISMISSED** [review]
Cool

**Review by Alex-Thacker — APPROVED** [review]
gooooooooooooooooooooooooooooooooooooooood

**Review by SamBritt — APPROVED** [review]
luuk

**Pull request merged**
