### PR TITLE
Cm friends

### PR DESCRIPTION
**Pull request by bluemorgan23**
# Description

This branch contains functionality for the friends component. Also the registration form is included with this merge request.

Applies to issue # 6 / 8

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions

1. `git fetch --all`
2. `git checkout cm-friends`
3. `npm start`
4. Test registration form by trying to register with your username and password. Then actually register a new account and make sure it takes you to the app and POSTS a new user
5. Look at the friends section. Test functionality of the search as well as the delete.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by rosewisotzky — CHANGES_REQUESTED** [review]
Comments are great! I love love love it! They cured my existential dread and my slipped disc in my back! The delete on friends work but the search function gives me the error of "this.props.addFriend is not a function" :(

**Review by rosewisotzky — DISMISSED** [review]
GORGEOUS!!!!!!!!! GREAT JOB!!!!!!!

-pep pep

**Review by rosewisotzky — APPROVED** [review]
WoOooOoOoOoO

**Review by Alex-Thacker — APPROVED** [review]
works

**Pull request merged**
